import { Badge } from "@/components/ui/badge";
import Image from "next/image";
import Link from "next/link";
import React from "react";

const Hero = () => {
  return (
    <section className="py-4 lg:py-14">
      <div className="mx-auto lg:max-w-7xl w-full px-5 sm:px-10 md:px-12 lg:px-5 grid lg:grid-cols-2 lg:items-center gap-10">
        <div className="flex flex-col space-y-8 sm:space-y-10 lg:text-left max-w-2xl md:max-w-3xl mx-auto">
          <Badge variant="default" className="bg-black h-9 rounded-full px-8">
            # Cohort 2
          </Badge>
          <h1 className="text-4xl lg:text-6xl font-bold text-primary">
            Get Into Tech Summer Camp Cohort 2
          </h1>
          <p className=" flex text-black  text-lg md:font-normal max-w-lg">
            GetIntoTech Summer Camp empowers young learners with coding,
            robotics, and digital skills through hands-on workshops, mentorship,
            and innovation challenges.
          </p>
          <Link
            href="#"
            className="px-6 items-center h-12 rounded-3xl bg-primary text-white duration-300 ease-linear flex justify-center w-1/3"
          >
            Apply Now
          </Link>
        </div>
        <div className="flex aspect-square lg:aspect-auto lg:h-[36rem] relative">
          <div className="w-3/5 h-[80%] rounded-xl overflow-clip border-6 border-white z-30">
            <Image
              src="/images/heromain.jpg"
              alt="Students working on a project"
              width={1200}
              height={1200}
              className="w-full h-full object-cover z-30"
            />
          </div>
          <div className="absolute right-0 bottom-0 h-[calc(100%-50px)] w-4/5 rounded-xl overflow-clip border-3 border-white z-10">
            <Image
              src="/images/heromain.jpg"
              alt="Students Working on a"
              height={1300}
              width={1300}
              className="z-10 w-full h-full object-cover"
            />
          </div>
        </div>
        <div className="absolute top-0 right-0 z-0 opacity-40">
          <svg
            width="548"
            height="578"
            viewBox="0 0 548 578"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <circle
              cx="4"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="4"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="34"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="64"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="94"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="124"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="154"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="184"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="214"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="244"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="274"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="304"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="334"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="364"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="394"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="424"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="454"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="484"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="514"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="544"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="4"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="34"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="64"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="94"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="124"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="154"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="184"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="214"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="244"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="274"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="304"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="334"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="364"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="394"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="424"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="454"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="484"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="514"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
            <circle
              cx="544"
              cy="574"
              r="4"
              fill="#9747FF"
              fill-opacity="0.19"
            ></circle>
          </svg>
        </div>
      </div>
    </section>
  );
};

export default Hero;
